# Generated by Django 5.0 on 2023-12-25 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=40)),
                ('book_no', models.IntegerField()),
                ('book_author', models.CharField(max_length=40)),
                ('book_price', models.IntegerField()),
            ],
        ),
    ]
